### ISSUE TITLE
Be able to translate the popup content with WPML

### ISSUE THREAD

**Issue by mattmary** [kevinweber/wbounce#20]
Hello,

thank you for this amazing plugin.
We use it in an international context (our translations are managed with the WPML plugin).
Unfortunately, we are not able to provide a different version for every language: the popin is always in English.
Could you make it compatible with WPML?

Kind regards

**Comment by kevinweber** [comment]
Hi @mattmary, thank you reaching out. The modal content technically supports being translated (https://github.com/kevinweber/wbounce/blob/master/frontend/class-frontend.php#L37) using the ´wbounce´ translation string (https://github.com/kevinweber/wbounce/blob/master/wbounce.php#L30). But maybe it doesn't really work – it's been a while since I worked on this – and it would certainly be nice to have a UI that makes adding translations easy. At this point though, I'm not available to develop new features. If someone from your team would like to make a contribution to this open source project, I'm happy to review and publish the improvement.
Best,
Kevin

**Comment by mattmary** [comment]
Hi @kevinweber 

Unfortunately, I was expecting so far a different approach than using a WordPress network approach (WPML is not configured like that).
I'll close this issue then, as I managed it through JavaScript variables.
