### ISSUE TITLE
no option to animate popup?

### ISSUE THREAD

**Issue by rahilwazir** [kevinweber/wbounce#9]
Is there a option to set animation when popup open/close?

**Comment by kevinweber** [comment]
No, there's no option yet. I once started implementing an option but that caused cross-browser compatibility issues, or some other kind of conflict. That's why I didn't publish it.
You see leftovers from that experiment in the source code (see uncommented lines in [wbounce.scss](https://github.com/kevinweber/wbounce/blob/master/css/wbounce.scss#L68)). I'm also considering to implement https://github.com/daneden/animate.css.

In the end, animations are a nice-to-have feature, and I'm focussed on other projects currently. But feel free to contribute to this repository :-)

**Comment by rahilwazir** [comment]
Hi, I have started working on animation feature and I'm almost there. But there seems to be little issue.

Following the issue [Animation not centered](https://github.com/daneden/animate.css/issues/291)

As you know there is `transform` property to `.modal-sub` element to align wBounce popup horizontally center. So animating with `animate.css`, the `transform` property gets overridden by `animate.css` which causes wBounce popup to move down a bit then get back to its proper position after animation finishes.

We need a way to center align both horizontally and vertically without `transform` property.

I'm thinking of using `display: flex` property but it has [no support for IE9](http://caniuse.com/#search=flex), I have tested on latest Chrome and Firefox and its working fine there.

What do you suggest?

**Comment by kevinweber** [comment]
Nice, I'm looking forward to see your results!
What about disabling the animation feature for every browser below IE10? For example, you can implement conditional tags to add a special IE class to the page. Then you can reset the animation for ".belowIE10 .animation" in CSS.
More about conditional tags: http://www.quirksmode.org/css/condcom.html and https://codex.wordpress.org/Conditional_Comment_CSS

Alternatively, the browser check can be done with JavaScript. If the check is positive (thus, browser is IE below IE10), then add a class to the body element. See http://stackoverflow.com/a/15983064/3266345 and https://snipt.net/wvega/add-a-class-to-the-body-with-javascript/

**Comment by kevinweber** [comment]
Pull request #10 is now merged and [published on WordPress.org](https://wordpress.org/plugins/wbounce/) as version 1.6.

**Comment by rahilwazir** [comment]
Thanks :smiley:
